---
dist: "xenial"
language: "python"
python:
    - "3.7"

services:
    - "docker"

install:
    - "pip install -r requires.txt"

# Verify that system is ready for system testing.
before_script:
#    - "pylint app/*.py"
    - "pytest --verbose src/test_db.py"
    - "./scripts/create-self-cert.sh"
    - "docker-compose up -d"
    - "docker container ls"

script:
    - "pytest --verbose src/test_orm.py"
    - "pytest --verbose tests/test_system.py"

after_script:
    - "docker-compose down"
...